# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: claude:claude-sonnet-4-6
clients:
- type: claude
  api_key: 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
